[build]
  command = "npm run create-env && npm run build"
  publish = "public"

[context.develop]
  environment = { API_URL = "https://beta.showpass.com/" }

[context.master]
  environment = { API_URL = "https://showpass.com/" }


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  
[[redirects]]
  from = "/*"
  to = "https://beta.showpass.com/"
  status = 200
  force = true
  headers = {X-From = "Netlify"}

[[headers]]
  # Define which paths this specific [[headers]] block will cover.
  for = "/*"
    [headers.values]
    Access-Control-Allow-Origin = "*"
