[build]
  command = "npm run create-env && npm run build"
  publish = "public"

[context.develop]
  environment = { API_URL = "https://beta.showpass.com/" }

[context.master]
  environment = { API_URL = "https://showpass.com/" }

[[redirects]]
  from = "/?hello=test"
  to = "https://google.com"
  status = 200
